INSERT INTO resources (title, description, url, category, user_id) VALUES ('Google', 'Tried and true.', 'https://www.google.com', 'favourites', 1);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('Colour Picker', 'Find a nice shade, tone, or complimentary colour.', 'https://www.colorhexa.com/', 'tools', 2);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('YouTube', 'Watch stuff; learn, take a break, laugh.', 'https://www.youtube.com', 'tools', 3);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('MUI CSS', 'A simple component library.', 'https://www.muicss.com/docs/v1/css-js/boilerplate-htmlhttps://www.muicss.com/docs/v1/css-js/boilerplate-html', 'styles', 4);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('GitHub', 'EXTREMELY important. Committing all day everyday.', 'https://github.com/', 'tool', 5);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('DDQ', 'Dev Duck Quack - the best resource wall ever.', 'http://localhost:8080/', 'reference', 6);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('Random User Photos', 'Get some randos on your page.', 'https://randomuser.me/photos', 'styles', 7);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('Stack Overflow', 'But the good kind - go get some community help.', 'https://stackoverflow.com/', 'reference', 8);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('CSS Grid Guide', 'Align.. Rows.. um.. Yeah, check this out.', 'https://css-tricks.com/snippets/css/complete-guide-grid/', 'styles', 9);
INSERT INTO resources (title, description, url, category, user_id) VALUES ('MDN Web Docs', 'The GOAT of documentation - visit frequently.', 'https://developer.mozilla.org/en-US/docs/Web', 'reference', 10);
